### ISSUE TITLE
Mobile first

### ISSUE THREAD

**Issue by isnotafunction** [fac-14/JEAH_DB_week#28]
These days it's good to do mobile first and then adapt for wider screens

![screen shot 2018-08-10 at 09 50 28](https://user-images.githubusercontent.com/19745717/43950200-90a37b60-9c87-11e8-8254-3a25a4072893.png)

**Comment by Brymon** [comment]
Agreed
![screen shot 2018-08-10 at 10 50 54](https://user-images.githubusercontent.com/26569161/43951550-5b33274c-9c8b-11e8-8e13-8d010b88b460.png)
